# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Tip: in case of problems with Dependabot not running, first check https://github.com/VirtusLab/git-machete-intellij-plugin/settings/actions

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: weekly
    target-branch: develop
    groups:
      deps:
        patterns:
          # To lump all updated dependencies together into a single PR (instead of PR-per-dependency)
          - "*"
  - package-ecosystem: "gradle"
    directory: "/buildSrc/"
    schedule:
      interval: weekly
    target-branch: develop
    groups:
      deps:
        patterns:
          # To lump all updated dependencies together into a single PR (instead of PR-per-dependency)
          - "*"
