# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Tip: in case of problems with Dependabot not running, first check https://github.com/VirtusLab/git-machete-intellij-plugin/settings/actions

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - PawelLipski
    target-branch: develop
    groups:
      deps:
        patterns:
          # To lump all updated dependencies together into a single PR (instead of PR-per-dependency)
          - "*"
    ignore:
      # slf4j-simple 2.0.0 isn't compatible with slf4j-api v1.x.y, which is still pulled in by our dependencies.
      # See https://www.slf4j.org/faq.html#changesInVersion200.
      # We could theoretically also override slf4j-api to v2.0.0 in tests that rely on slf4j-simple...
      # but that's not worth it yet, esp. given that IntelliJ still runs on slf4j-api v1.x.y as of 2022.2.
      - dependency-name: "org.slf4j:slf4j-simple"
        update-types: ["version-update:semver-major"]
      # Let's keep Kotlin plugin version equal to the version of Kotlin embedded into the Gradle version we use.
      # This lets us avoid warning:
      #   WARNING: Unsupported Kotlin plugin version.
      #   The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.9.22`
      #   that might work differently than in the requested version `1.9.23`.
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
      - dependency-name: "org.checkerframework:checker"
        version: "3.49.2"
      - dependency-name: "org.checkerframework:checker-qual"
        version: "3.49.2"
  - package-ecosystem: "gradle"
    directory: "/buildSrc/"
    schedule:
      interval: daily
    reviewers:
      - PawelLipski
    target-branch: develop
    groups:
      deps:
        patterns:
          # To lump all updated dependencies together into a single PR (instead of PR-per-dependency)
          - "*"
    ignore:
      # As per https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library:
      # "If a plugin supports multiple platform versions, it must (...) target the lowest bundled stdlib version".
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
