#!/usr/bin/env bash

set -e -o pipefail -u

# As per git hook spec, we can rely on this script being executed in the main repository dir.
source scripts/utils.sh

[[ ${1-} ]] || die "usage: $(basename "$0") <branch-name>"
branch=$1

function ansi_esc {
  [[ ${ASCII_ONLY-} = true ]] || echo -n "$1"
}
dim=$(ansi_esc '\033[2m')
endc=$(ansi_esc '\033[0m')

echo -ne "${dim}v$(extract_version_from_git_revision "$branch" || echo '???')${endc}"
