#!/usr/bin/env bash

set -e -o pipefail -u

# As per git hook spec, we can rely on this script being executed in the main repository dir.
# Let's skip the grep check, as:
# 1. neither `grep` nor `git grep` is needed in this simple script
# 2. there's a performance overhead in checking for grep/git grep which isn't desired in a frequently executed hook
# 3. `PATH` might not be set up correctly in popen-style executions of bash,
#    which might lead to a wrong `grep` binary getting executed
source scripts/utils.sh --skip-grep-check

[[ ${1-} ]] || die "usage: $(basename "$0") <branch-name>"
branch=$1

function ansi_esc {
  [[ ${ASCII_ONLY-} = true ]] || echo -n "$1"
}
dim=$(ansi_esc '\033[2m')
endc=$(ansi_esc '\033[0m')

echo -ne "${dim}v$(extract_version_from_git_revision "$branch" || echo '???')${endc}"
