[versions]
checker = "3.54.0"
junit = "6.0.3"
remoteRobot = "0.11.23"

[libraries]
# Libraries
apacheCommonsText = "org.apache.commons:commons-text:1.15.0"
archunit = "com.tngtech.archunit:archunit:1.4.1"
betterStrings = "com.antkorwin:better-strings:0.5"
checker = { module = "org.checkerframework:checker", version.ref = "checker" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker" }
commonsIO = "commons-io:commons-io:2.21.0"
jetbrains-annotations = "org.jetbrains:annotations:26.1.0"
jgit = "org.eclipse.jgit:org.eclipse.jgit:7.5.0.202512021534-r"
junit4 = "junit:junit:4.13.2"
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
kodein = "org.kodein.di:kodein-di-jvm:7.31.0"
kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.10.2"
kotlinxSerializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0"
lombok = "org.projectlombok:lombok:1.18.42"
mockito = "org.mockito:mockito-junit-jupiter:5.22.0"
okhttp = "com.squareup.okhttp3:okhttp:5.3.2"
remoteRobot-client = { module = "com.intellij.remoterobot:remote-robot", version.ref = "remoteRobot" }
remoteRobot-serverPlugin = { module = "com.intellij.remoterobot:robot-server-plugin", version.ref = "remoteRobot" }
slf4j-lambda = "kr.pe.kwonnam.slf4j-lambda:slf4j-lambda-core:0.1"
slf4j-mock = "org.simplify4u:slf4j-mock:2.4.0"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.17"
vavr = "io.vavr:vavr:1.0.1"

# Note that certain plugins are also pulled in via buildSrc,
# where they aren't really `apply`-ed as plugins, but rather added to classpath as plugin packages;
# see https://docs.gradle.org/current/samples/sample_convention_plugins.html#things_to_note.
[plugins]
jetbrains-changelog = "org.jetbrains.changelog:2.5.0"
jetbrains-grammarkit = "org.jetbrains.grammarkit:2023.3.0.3"
jetbrains-intellij = "org.jetbrains.intellij.platform:2.11.0"
taskTree = "com.dorongold.task-tree:4.0.1"
