[versions]
junitJupiter = "6.0.0"

[libraries]
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitJupiter" }
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3"
# Plugin packages
# This way of applying the plugins is needed for the build-related code in buildSrc/src/main/,
# see https://docs.gradle.org/current/samples/sample_convention_plugins.html#things_to_note.
pluginPackages-checkerFramework = "org.checkerframework:checkerframework-gradle-plugin:0.6.60"
pluginPackages-grgit = "org.ajoberstar.grgit:grgit-gradle:5.3.3"
pluginPackages-spotless = "com.diffplug.spotless:spotless-plugin-gradle:8.0.0"

[plugins]
taskTree = "com.dorongold.task-tree:4.0.1"
