{
  parserClass="com.virtuslab.gitmachete.frontend.file.grammar.MacheteGeneratedParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="MacheteGenerated"
  psiImplClassSuffix="Impl"
  psiPackage="com.virtuslab.gitmachete.frontend.file.grammar"
  psiImplPackage="com.virtuslab.gitmachete.frontend.file.grammar.impl"

  elementTypeHolderClass="com.virtuslab.gitmachete.frontend.file.grammar.MacheteGeneratedElementTypes"
  elementTypeClass="com.virtuslab.gitmachete.frontend.file.grammar.MacheteElementType"
  tokenTypeClass="com.virtuslab.gitmachete.frontend.file.grammar.MacheteTokenType"
}

simpleFile ::= item_*

// Even if we don't have comments in our machete file, the COMMENT element must be here - language parser definition
// (in file MacheteParserDefinition) enforces us to define element that represent comments
private item_ ::= (entry|COMMENT|(INDENTATION? EOL))

entry ::= INDENTATION? branch CUSTOM_ANNOTATION?

branch ::= PREFIX? NAME
