#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

parse_version_from_current_wd head

if [[ ${CIRCLE_BRANCH-} ]]; then
  cb=$CIRCLE_BRANCH
else
  cb=$(git symbolic-ref --short HEAD)
fi

if [[ $cb == master || $cb == release/* || $cb == hotfix/* || $cb == backport/* ]]; then
  [[ -z $head_pre_release ]] || \
    die 'Pre-release version is not allowed on master/release/hotfix/backport branch tip'
elif [[ $cb != develop ]]; then
  # Tip of develop can legitimately have either a pre-release version (when a regular PR has been merged)
  # or a release version (when a backport PR has been merged).
  [[ $head_pre_release ]] || \
    die 'Non-{develop/master/release/hotfix/backport} branch tip must have a pre-release version (a.b.c-d, not a.b.c)'
fi
