#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

found=0
for file in $(git grep -Il ''); do
  if ! [[ $(tail -c1 $file | xxd -p) =~ 0[ad] ]]; then
    echo "$file"
    found=1
  fi
done
if [[ $found -ne 0 ]]; then
  die '\nThe above non-binary files do not end with a newline character, please tidy up'
fi
