#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

exit_code=0

for file in $(git ls-files '*.astub'); do
  annotations_imported_in_file=$(grep -Po '(?<=import ).*(?=;)' "$file" | rev | cut -d. -f1 | rev | sort -u)
  annotations_used_across_file=$(grep -Po '(?<=@)[a-zA-Z0-9.]*' "$file" | sort -u)

  # Print the lines missing from the first input but present in the second
  unimported_annotations=$(comm -13 <(echo "$annotations_imported_in_file") <(echo "$annotations_used_across_file"))
  if [[ $unimported_annotations ]]; then
    echo "$file: $(echo -n "$unimported_annotations" | tr '\n' ',' | sed 's/,/, /g') must be imported explicitly"
    exit_code=1
  fi

  # Print the lines present in the first input but missing from the second
  unused_annotations=$(comm -23 <(echo "$annotations_imported_in_file") <(echo "$annotations_used_across_file"))
  if [[ $unused_annotations ]]; then
    echo "$file: $(echo -n "$unused_annotations" | tr '\n' ',' | sed 's/,/, /g') imported but unused"
    exit_code=1
  fi
done

exit $exit_code
