#!/usr/bin/env bash

set -e -o pipefail -u

awk_script="$(cat <<'EOF'

  FNR == 1 { prev_non_empty = "" }

  ( /^ {3}/ && prev_non_empty !~ /^ {2}/ ) || ( /^ {5}/ && prev_non_empty !~ /^ {4}/ ) {
    print FILENAME ":" FNR ": likely three or four spaces used for indent instead of two"
    exit_code = 1
  }

  /^.+$/ { prev_non_empty = $0 }

  END { exit exit_code }

EOF
)"

git ls-files \
  ':!*.flex' ':!gradlew' ':!*.java' ':!*.kt' ':!*.md' \
  ':!plugin-verifier.gradle' '!*.scala' ':!scripts/setup-multiroot-sandbox' \
  ':!*.svg' ':!testCommon/src/test/resources/*.sh' ':!*.xml' \
   | xargs awk "$awk_script"
