#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

if [[ ${CI_PULL_REQUEST-} ]]; then
  # In case of a PR build, CI_PULL_REQUEST should be a link of the form https://github.com/VirtusLab/git-machete-intellij-plugin/pull/123
  pr_num=${CI_PULL_REQUEST##*/}
  # A hackish way to derive base commit of a PR on Github: first, fetch the ref pointing to PR head commit merged to the base,
  # available on GH under refs/pull/<pr-number>/merge...
  if git fetch --quiet origin refs/pull/$pr_num/merge:refs/remotes/origin/pull-$pr_num/merge; then
    #  ... and then extract the first parent of that hash (the second parent is just our current HEAD commit).
    base_revision="origin/pull-${pr_num}/merge^1"
  else
    # Fetching refs/pull/<pr-number>/merge sometimes spuriously fails, possibly due to eventual consistency on GitHub.
    # Let's fall back to master in such cases.
    base_revision=origin/master
  fi

elif [[ ${CIRCLE_BRANCH-} == master ]]; then
  exit 0

elif git machete show up &>/dev/null; then
  base_revision=$(git machete show up 2>/dev/null)

elif command -v hub &>/dev/null; then
  # Fall back to master if no PR is open for the current branch.
  base_revision=$(hub pr show --format=%B 2>/dev/null || echo master)

else
  base_revision=origin/master
fi


base_commit_short_hash=$(git rev-parse --short "$base_revision")
base_desc="$base_revision (commit $base_commit_short_hash)"

parse_version_from_current_wd head
parse_version_from_git_revision base "$base_commit_short_hash"

[[ $head_major -gt $base_major ]] && exit 0
[[ $head_major -eq $base_major ]] || \
  die "Major version $head_major must not be lower than $base_major in $base_desc"

[[ $head_minor -gt $base_minor ]] && exit 0
[[ $head_minor -eq $base_minor ]] || \
  die "Minor version $head_minor must not be lower than $base_minor in $base_desc"

[[ $head_patch -gt $base_patch ]] && exit 0
[[ $head_patch -eq $base_patch ]] && \
  die "Version must not be identical as in $base_desc" || \
  die "Patch version $head_patch must not be lower than $base_patch in $base_desc"
