#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

# Note: this should be kept in sync with frontendUi/build.gradle.
# We're not including any 193.* (aka 2019.3) release here since that's the version we're currently building against anyway
# (see build.gradle -> subprojects.ext.intellijVersion).
intellij_versions=(201.6668.121)

verifier_version=1.233
plugin_version=$(extract_version_from_build_gradle_stdin < version.gradle)
plugin_zip=$(echo frontendUi/build/distributions/git-machete-intellij-plugin-${plugin_version}*.zip)

[[ -f $plugin_zip ]] || die "File $plugin_zip not found, run 'buildPlugin' Gradle task"

set -x

# See https://github.com/JetBrains/intellij-plugin-verifier
verifier_dir="./.cache/intellij-verifier"
mkdir -p $verifier_dir

verifier_jar_path=$verifier_dir/verifier-all.jar
if ! [[ -f $verifier_jar_path ]]; then
  curl -fsL -o $verifier_jar_path https://dl.bintray.com/jetbrains/intellij-plugin-service/org/jetbrains/intellij/plugins/verifier-cli/${verifier_version}/verifier-cli-${verifier_version}-all.jar
fi

for iv in ${intellij_versions[*]}; do
  year=20${iv:0:2}
  release=${iv:2:1}
  idea_dir=idea-IC-${iv}
  if ! [[ -d $idea_dir ]]; then
    # Released packages apparently aren't available under version.build file name, only under year.release name
    # EAP packages apparently aren't available under year.release file name, only under version.build name
    {
      curl -fsL https://download.jetbrains.com/idea/ideaIC-${year}.${release}.tar.gz \
      || curl -fsL https://download.jetbrains.com/idea/ideaIC-${iv}.tar.gz
    } | tar xzf -
  fi

  java -jar "$verifier_jar_path" check-plugin -vrd "frontendUi/build/verification-$(date +%F_%T)" -runtime-dir "${idea_dir}/jbr/bin" "${plugin_zip}" "${idea_dir}"
done
