#!/usr/bin/env bash

set -u

vavrEnforcingModules=('branchLayoutApi' 'branchLayoutImpl')

for module in ${vavrEnforcingModules[*]}
do
  result=$(git grep -n 'java\.util\.\(List\|Optional\)' "$module/*.java")
  result_count=$(echo "$result" | wc -l)
  if [[ $result ]]; then
    echo "Vavr enforcer result:"
    echo "$result_count prohibited java.util use(s) has been detected:"
    echo "$result"
    exit 1
  fi
done
