#!/usr/bin/env bash

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

if git grep --files-without-match '^   \* Expects DataKeys:$' -- '*Action.java'; then
  die '\nProvide a Javadoc documenting the `DataKey`s required by `actionPerformed` in the above files.'
fi
