#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

found=0
for d in $(grep -o '_.' frontendActions/src/main/resources/actions/ResourceBundle.properties | tr '[:upper:]' '[:lower:]' | sort | uniq -d); do
  error 'ResourceBundle.properties contains duplicated key shortcut:' $d
  found=1
done

if [[ $found -ne 0 ]]; then
  die 'Use unique key shortcuts for actions'
fi
