#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

awk_script="$(cat <<'EOF'

  ( /^    / && prev_non_empty !~ /^  / ) || ( /^      / && prev_non_empty !~ /^    / ) {
    print file ":" NR ": likely four spaces used for indent instead of two"
    exit_code = 1
  }

  /^.+$/ { prev_non_empty = $0 }

  END { exit exit_code }

EOF
)"

exit_code=0
for file in $(git ls-files '*.astub' '*.gradle' scripts/ ':!scripts/setup-multiroot-sandbox'); do
  awk -v "file=$file" "$awk_script" < "$file" || exit_code=1
done
exit $exit_code
