#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

if git grep --name-only --all-match -e '@ToString' --or -e ' extends ' -- '*.java' | \
  xargs git grep --files-without-match '@ToString(callSuper = true)' --; then
    die 'A @ToString annotation found in the above classes but no @ToString(callSuper = true) present even though their superclass is NOT java.lang.Object'
fi
