#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

if git grep 'private va[lr]' -- '*.kt' ':!buildSrc'; then
  die 'Private fields are apparently unsafe (likely to cause a runtime error) in Kotlin due to https://youtrack.jetbrains.com/issue/KT-29016'
fi
