#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

if git grep --files-with-matches '^@CustomLog$' -- '*.java' | xargs git grep --word-regex --files-without-match LOG; then
  die 'The above Java sources contain @CustomLog, but LOG is never referenced'
fi
