#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

class_names=$(git ls-files '*.java' | xargs basename -s .java | sort | tr '\n' '|' | sed 's/.$//')

# Let's allow for class names preceded with `action.GitMachete.` (for property keys).
if git grep -PHn '^[^"]*"[^"$]*(?<!(action|string)\.GitMachete\.)\b('"$class_names"')\b' -- '*.java' ':!frontend/base/src/main/java/com/virtuslab/gitmachete/frontend/defs' ':!frontend/base/src/main/java/com/virtuslab/gitmachete/frontend/resourcebundles'; then
  die 'Avoid hardcoding class names in string literals, use more refactor-friendly Class#getSimpleName() instead'
fi
