#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

class_names=$(git ls-files '*.java' | xargs basename -s .java | sort | paste -sd'|')

if git grep -EHn  '^[^"]*"[^"$]*\<('"$class_names"')\>' -- '*.java' ':(exclude)./frontendDefs'; then
  die 'Avoid hardcoding class names in string literals, use more refactor-friendly Class#getSimpleName() instead'
fi
