#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

if git grep -EIn '\s+$'; then
  die 'The above lines contain trailing whitespace, please tidy up'
fi
