#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

# .gitconfig can be excluded since git config files are customarily indented with tabs rather than spaces
if git --no-pager grep -In $'\t' -- ':(exclude)./.gitconfig'; then
  die 'The above lines contain tab character (instead of spaces), please tidy up'
fi
