#!/usr/bin/env bash

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

if git --no-pager grep -EIn '\s+$'; then
  die '\nThe above lines contain trailing whitespace, please tidy up'
fi
