#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

if git grep -En '^ +[^/*"]*\bclass ' -- '*.java' | grep -v '\bstatic '; then
  error 'Inner (non-static nested) classes are currently unsafe & discouraged due to https://github.com/typetools/checker-framework/issues/3407'
  die 'Consider using a static nested class and passing a reference to the enclosing object (or to the fields thereof) explicitly.'
fi
