#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

class_names=$(git ls-files '*.java' | xargs basename -s .java | sort | paste -sd'|')

# Let's allow for class names preceded with `action.GitMachete.` (for property keys).
if git grep -PHn '^[^"]*"[^"$]*(?<!(action|string)\.GitMachete\.)\b('"$class_names"')\b' -- '*.java' ':!frontendDefs' ':!frontendResourceBundles'; then
  die 'Avoid hardcoding class names in string literals, use more refactor-friendly Class#getSimpleName() instead'
fi
