#!/usr/bin/env bash

set -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh


# Find the strings that have the property value wrapped in double quotes (")
values_wrapped_in_double_quotes=$(git grep -Ph -e '=".*"$' -- '*.properties')

if [[ $values_wrapped_in_double_quotes ]]; then
  echo "$values_wrapped_in_double_quotes"
  die "The above property keys have a property value wrapped in double quotes (\"). Remove unnecessary wrapping"
fi
