#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

if git grep -n "['\"]!" scripts/; then
  die 'Did you mean :!... (preceded with a colon) for this file pattern?'
fi
