#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

# See https://stackoverflow.com/a/3208902/2750812 for the purpose of LC_ALL=C.
# -P (perl mode) is needed to allow for hex codes in character ranges.
# -I is passed to skip binary files from grep.
# Excluding tab (detected in a separate script for a clearer error message and a different set of whitelisted files).
# gradlew is whitelisted since it contains e.g. a copyright character.
# README.md is whitelisted since it contains emojis.
# CONTRIBUTING.md is whitelisted since it contains Mac key symbols.
if LC_ALL=C git grep -PIn '[^\x09\x20-\x7F]' -- ':!gradlew' ':!README.md' ':!CONTRIBUTING.md'; then
  die 'The above lines contain character(s) outside of 0x20-0x7F range, please tidy up'
fi
