#!/usr/bin/env bash

set -e -o pipefail -u

intellij_version=${1-} # can be skipped; the same IntelliJ version that the plugin has been built against will be assumed

log=~/gradlew-runIdeForUiTests.log
# Let's make sure there is no state left from the previous test runs.
rm -rf build/idea-sandbox/

# If we're on CI, run IDE on X Virtual Framebuffer; otherwise, open a regular window.
# --auto-servernum is deprecated in favor of --auto-display,
# but unfortunately xvfb-run available for Debian Buster (base of our CI image) doesn't support the latter.
command=${CI:+xvfb-run --auto-servernum}
$command ./gradlew -PintellijVersionForRunIde=$intellij_version runIdeForUiTests >$log 2>&1 &
# $! expands to the PID of the last process executed in the background
ide_pid=$!

# The test will gracefully close the IDE instance if successful,
# but we still need to kill the IDE instance in case that test was not successful AND the IDE is still running.
function finish {
  if ps -p $ide_pid >/dev/null 2>&1; then
    kill $ide_pid
  fi
}
trap finish EXIT

last_line=0
# Let's wait until Remote Robot plugin living within the IDE starts listening.
while ! nc -z localhost 8080; do
  sleep 0.5
  tail -n+$((last_line+1)) $log
  last_line=$(wc -l < $log)
done

./gradlew -PenableUiTests --info :uiTests:test
