#!/usr/bin/env bash

set -e -o pipefail -u

# We don't want `less` to open for `git grep` results in the below scripts when running locally.
export GIT_PAGER=cat

# Note that we could easily rely on `set -e`, but then we'd have a fail-fast behavior,
# while we want to display all failures collectively (and still fail the entire suite if any individual script failed).
failed=""

function _() {
  script=$1
  option=${2-}
  if [[ $option == "--skip-in-pre-commit-hook" ]] && [[ $0 == *.git/hooks/pre-commit ]]; then
    echo "(skipping $script as we are running in a git pre-commit hook)" >&2
    return
  fi
  echo "> $script" >&2
  if ! eval "./scripts/$script"; then
    failed="$failed, $script"
  fi
}

_ enforce-astub-explicit-annotation-import
_ enforce-change-notes-updated-on-pr-to-master
_ enforce-indent-two-spaces-outside-java
_ enforce-issue-number-for-todos
_ enforce-newline-at-eof
_ enforce-properties-keys-with-valid-class-names
_ enforce-settings-gradle-match-directories
_ enforce-shell-scripts-pass-shellcheck
_ enforce-version-bump

# This one is needed as a pull request check. So, it should not run as a git pre-commit hook.
_ prohibit-direct-merges-to-master --skip-in-pre-commit-hook
_ prohibit-java-class-name-hardcode-in-strings
_ prohibit-java-code-commented-out
_ prohibit-java-lines-split-needlessly
_ prohibit-java-unused-custom-log
_ prohibit-kotlin-undefined-property-keys
_ prohibit-kotlin-unsafe-cast
_ prohibit-non-ascii-characters
_ prohibit-properties-unused-keys
_ prohibit-tab-character
_ prohibit-trailing-whitespace

_ validate-icons
# This one needs to connect to the linked websites and can potentially run long,
# let's skip it when this script is executed as git pre-commit hook.
_ validate-markdown-links --skip-in-pre-commit-hook
_ validate-markdown-values

if [[ $failed ]]; then
  echo "${failed#, } failed" >&2
  exit 1
fi
