#!/usr/bin/env bash

set -e

# `$-` yields the list of the options of the current shell; we'll only interested in whether `x` is present
x_option=${-//[^x]/}

./scripts/enforce-change-notes-updated-on-release-pr
./scripts/enforce-explicit-annotation-import-in-astubs
./scripts/enforce-indent-two-spaces-outside-java
./scripts/enforce-issue-number-for-todos
./scripts/enforce-newline-at-eof
bash ${x_option:+-x} ./scripts/enforce-pre-release-version-correct-use  # pass -x option if this script is run with -x option itself
bash ${x_option:+-x} ./scripts/enforce-version-bump
./scripts/prohibit-class-name-hardcode-in-strings
./scripts/prohibit-tab-character
./scripts/prohibit-trailing-whitespace
