#!/usr/bin/env bash

# Usage:
# $ ./scripts/run-ui-tests [<intellij-version> [<only-tests>]]

# If <only-tests> is present and non-empty, only the UI test methods
# whose names start with the given prefix will be executed (instead of all UI test methods).

set -e -o pipefail -u

intellij_version=${1-}
test_method_prefix=${2-}

if [[ ${CI-} == true ]]; then
  export IDEPROBE_DISPLAY=xvfb
fi

only_tests_flag=${test_method_prefix:+--tests *.$test_method_prefix*}
./gradlew \
  -PenableUiTests \
  -PintellijVersionForUiTests="$intellij_version" \
  --info \
  uiTests:test $only_tests_flag
