#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/sandbox-setup-utils.sh

sandboxDir=machete-sandbox

init

# Review
newremote scenario-1
create_repo scenario-1
git remote add origin ~/$sandboxDir/scenario-1-remote

create_branch master
  commit 'Init'
  push
git checkout master
create_branch sticky-header
  commit 'Add sticky-header'
  push
create_branch fancy-footer
  commit 'Add fancy footer'
  push
git checkout master
create_branch common-scripts
  commit 'Add common-scripts'
  push
git checkout fancy-footer
git branch -d common-scripts

cat >.git/machete <<EOF
master
  sticky-header PR #2
    fancy-footer PR #3
EOF

# Branch update
newremote scenario-2
create_repo scenario-2
git remote add origin ~/$sandboxDir/scenario-2-remote

create_branch master
  commit 'Init'
  push
create_branch common-scripts
  commit 'Add common-scripts'
  push
git checkout master
  git merge --ff-only -
  git branch -d common-scripts
  git reset --hard HEAD~1
  git rev-parse HEAD > ~/$sandboxDir/scenario-2/.git/refs/remotes/origin/master
  git rev-parse HEAD
  git rev-parse origin/common-scripts > ~/$sandboxDir/scenario-2-remote/refs/heads/master
create_branch sticky-header
  commit 'Add sticky-header'
  push
create_branch fancy-footer
  commit 'Add fancy footer'
  push
cat >.git/machete <<EOF
master
  sticky-header PR #2
    fancy-footer PR #3
EOF

# Stacker PRs
newremote scenario-3
create_repo scenario-3
git remote add origin ~/$sandboxDir/scenario-3-remote

create_branch master
  commit 'Init'
  commit 'Add common-scripts'
  push
create_branch sticky-header
  commit 'Add sticky-header'
  push
create_branch fancy-footer
  commit 'Add fancy footer'
  push
git checkout sticky-header
  commit 'Fix typos'

cat >.git/machete <<'EOF'
master
  sticky-header PR #2
    fancy-footer PR #3
EOF

# Merge (ff)
newremote scenario-4
create_repo scenario-4
git remote add origin ~/$sandboxDir/scenario-4-remote

create_branch master
  commit 'Init'
  commit 'Add common-scripts'
 push
create_branch sticky-header
  commit 'Add sticky-header'
  commit 'Fix typos'
  push
create_branch fancy-footer
  commit 'Add fancy footer'
  push

cat >.git/machete <<'EOF'
master
  sticky-header PR #2
    fancy-footer PR #3
EOF
