#!/usr/bin/env bash

set -e

sandboxDir=machete-sandbox

create_branch() {
  git checkout -b $1
}

commit() {
  b=$(git symbolic-ref --short HEAD)
  f=${b/\//-}-${1}-${2}.txt
  touch $f
  git add $f
  git commit -m "$*"
}

create_repo() {
  dir=$sandboxDir/$1
  mkdir ~/$dir
  cd ~/$dir
  opt=$2
  git init $opt
}

newremote() {
  dir=$sandboxDir/$1-remote
  mkdir ~/$dir
  cd ~/$dir
  git init --bare
}

push() {
  b=$(git symbolic-ref --short HEAD)
  git push -u origin $b
}

init() {
  rm -fr /tmp/_$sandboxDir
  mv -f ~/$sandboxDir /tmp/_$sandboxDir || true
  mkdir ~/$sandboxDir
}

init

newremote filter-service
create_repo filter-service
git remote add origin ~/$sandboxDir/filter-service-remote

create_branch root
  commit Root
create_branch develop
  commit Develop commit
create_branch allow-ownership-link
  commit Allow ownership links
  push
create_branch build-chain
  commit Build arbitrarily long chains
git checkout allow-ownership-link
  commit 1st round of fixes
git checkout develop
  commit Other develop commit
  push
create_branch call-ws
  commit Call web service
  commit 1st round of fixes
  push
create_branch drop-constraint # not added to the machete file
  commit Drop unneeded SQL constraints
git checkout call-ws
  commit 2nd round of fixes

git checkout root
create_branch master
  commit Master commit
  push
create_branch hotfix/add-trigger
  commit HOTFIX Add the trigger
  push
  git commit --amend -m 'HOTFIX Add the trigger (amended)'

cat >.git/machete <<EOF
develop
    allow-ownership-link PR #123
        build-chain
    call-ws PR #124
master
    hotfix/add-trigger PR #121
EOF

git branch -d root

echo
echo
git machete status $1
echo
echo

newremote generator-service
create_repo generator-service
git remote add origin ~/$sandboxDir/generator-service-remote

create_branch root
  commit Root
create_branch develop
  commit 'Develop commit (probably empty)'
create_branch forbid-ownership-link
  commit Forbid ownership links
  push
create_branch destroy-chain
  commit Destroy arbitrarily long chains
git checkout forbid-ownership-link
  commit n-th round of fixes
git checkout develop
  commit Other develop commit - this one too
  push
create_branch send-a-pigeon-for-ws
  commit Send a pigeon for web service
  commit 1st round of bugs
  push
git checkout forbid-ownership-link
create_branch toggle-rain
  commit toggle
  commit toggle 2
  push
  commit toggle 3
create_branch make-coffee
  commit Get water
  commit Search for help
  push
git checkout forbid-ownership-link
create_branch go-home
  commit run
  commit ide
  push
git checkout forbid-ownership-link
create_branch add-constraint # not added to the machete file
  commit Add unneeded SQL constraints
git checkout send-a-pigeon-for-ws
  commit 2nd round of bugs

git checkout root
create_branch master
  commit 'Restore configs'
  push
create_branch coldfix/knor
  commit pudliszki
  push
create_branch hotfix/remove-trigger
  commit HOTFIX Remove the trigger
  push
  git commit --amend -m 'HOTFIX Remove the trigger (amended)'

cat >.git/machete <<EOF
develop
    forbid-ownership-link PR #123
        send-a-pigeon-for-ws #70
    destroy-chain
        toggle-rain PR #21
            make-coffee PR #37
        go-home PR #124
master
    coldfix/knor PR #72
        hotfix/remove-trigger PR #13
EOF


git branch -d root

echo
echo
git machete status $1
echo
echo
