#!/usr/bin/env bash

set -e

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/sandbox-setup-utils.sh

sandboxDir=machete-sandbox

init

newremote scenario-1
create_repo scenario-1
git remote add origin ~/$sandboxDir/scenario-1-remote

create_branch master
  commit 'Init'
  push
create_branch fancy-footer
  commit 'Add fancy footer'
  push
git checkout master
git merge --ff-only -
git branch -d fancy-footer
git reset --hard HEAD~1
git rev-parse HEAD > ~/$sandboxDir/scenario-1/.git/refs/remotes/origin/master
git rev-parse HEAD
create_branch sticky-header
  commit 'Add sticky-header'
  push
git rev-parse origin/fancy-footer > ~/$sandboxDir/scenario-1-remote/refs/heads/master

cat >.git/machete <<EOF
master
  sticky-header PR #2
EOF

newremote scenario-2
create_repo scenario-2
git remote add origin ~/$sandboxDir/scenario-2-remote

create_branch master
  commit 'Init'
  push
create_branch fancy-footer
  commit 'Add fancy footer'
  push
create_branch sticky-header
  commit 'Add sticky-header'
  push

cat >.git/machete <<EOF
master
  fancy-footer PR #1
    sticky-header PR #2
EOF

newremote scenario-3
create_repo scenario-3
git remote add origin ~/$sandboxDir/scenario-3-remote

create_branch master
  commit 'Init'
  push
create_branch fancy-footer
  commit 'Add fancy footer'
  push
create_branch sticky-header
  commit 'Add sticky-header'
  push

cat >.git/machete <<EOF
master
  fancy-footer PR #1
    sticky-header PR #2
EOF
