#!/usr/bin/env bash

set -e -o pipefail -u -x

# Using the conventions as per https://semver.org/
build_metadata=+$(git rev-parse --short HEAD)
# Retain '-SNAPSHOT' pre-release indicator after git commit hash for non-master builds.
[[ ${CIRCLE_BRANCH-} = master ]] && pre_release_indicator='' || pre_release_indicator=-SNAPSHOT
sed -i "/^\s*version '.*-SNAPSHOT'\$/ s/-SNAPSHOT/$pre_release_indicator$build_metadata/" build.gradle
