#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

files_with_toc=$(git grep --files-with-matches 'START doctoc' -- '**.md')
doctoc $files_with_toc
git --no-pager diff --exit-code HEAD -- $files_with_toc || {
  die Tables of contents in the above Markdown files are not up to date
}
