#!/usr/bin/env bash

set -e -o pipefail -u

self_dir=$(cd "$(dirname "$0")" &>/dev/null; pwd -P)
source "$self_dir"/utils.sh

icons_path='frontend/base/src/main/resources'
icon_files=$(git ls-files "$icons_path/*.svg")
declared_icons=$(git grep -Pho '(?<=Icon) .* (?=\= loadIcon)' -- 'frontend/base/src/main/java/com/virtuslab/gitmachete/frontend/icons/MacheteIcons.java')

for referenced_file in $(git grep -Pho '(?<=loadIcon\("/).*(?="\))' -- 'frontend/base/src/main/java/com/virtuslab/gitmachete/frontend/icons/MacheteIcons.java'); do
  referenced_file_path="$icons_path/$referenced_file"
  referenced_file_path_dark=${referenced_file_path%.svg}_dark.svg
  if [[ $icon_files != *"$referenced_file_path"* ]]; then
    die "Icon '$referenced_file' referenced from MacheteIcons.java is missing from resources!"
  fi
  if [[ $icon_files != *"$referenced_file_path_dark"* ]]; then
    die "Dark icon '$referenced_file' referenced from MacheteIcons.java is missing from resources!"
  fi

  files=($referenced_file_path $referenced_file_path_dark)
  for file in $files; do
    width=$(git grep -Pho '(?<=width=")[0-9]*(?=")' -- $file | head -1)
    height=$(git grep -Pho '(?<=height=")[0-9]*(?=")' -- $file | head -1)
    if [[ $width != 16 || $height != 16 ]]; then
      die "Icon '$file' has invalid dimensions ${width}x${height}. Required dimensions are 16x16!"
    fi
  done

done

for referenced_icon in $(git grep -Pho '(?<=icon="MacheteIcons\.).*(?=")' -- 'src/main/resources/META-INF/plugin.xml'); do
  if [[ ! $declared_icons =~ $referenced_icon ]]; then
    die "Icon 'MacheteIcons.$referenced_icon' referenced from plugin.xml is not declared in MacheteIcons.java!"
  fi
done
