#!/usr/bin/env bash

set -e -o pipefail -u

exit_code=0
for class in $(find . -name '*.class' -type f); do
  strings_output=$(strings $class)
  # This is also catching would-be interpolations written without the leading `$`.
  grep_output=$(grep -E '^.+\{.*\}' <<< "$strings_output" || true)
  if [[ $grep_output ]]; then
    echo "Class file $class likely contains the following unprocessed string interpolations:"
    echo "$grep_output"
    echo
    exit_code=1
  fi
done
exit $exit_code
